### ISSUE TITLE
CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views

### ISSUE THREAD

**Issue by alvindizon** [kroegerama/barcode-kaiteki#3]
Currently developing for an app that runs on a Android Lollipop (API 21)device, and I am getting the following exception:
```
E/AndroidRuntime: FATAL EXCEPTION: BarcodeAnalyzer
    Process: com.a.myapp, PID: 21325
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6375)
        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:921)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:4691)
        at android.view.View.invalidateInternal(View.java:11802)
        at android.view.View.invalidate(View.java:11766)
        at android.view.View.invalidate(View.java:11750)
        at com.kroegerama.kaiteki.bcode.views.ResultPointView.clear(ResultPointView.kt:58)
        at com.kroegerama.kaiteki.bcode.views.BarcodeView.onNoResult(BarcodeView.kt:77)
        at com.kroegerama.kaiteki.bcode.BarcodeAnalyzer.analyze(BarcodeAnalyzer.kt:55)
        at androidx.camera.core.ImageAnalysisNonBlockingCallback$1.run(ImageAnalysisNonBlockingCallback.java:150)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

Here's my Fragment:

```
public class KaitekiFragment extends BaseFragment<FragmentKaitekiBinding, ScanViewModel>
        implements BarcodeResultListener {

...
...
    @Override
    public void onStart() {
        super.onStart();
        BarcodeAlertDialogKt.showBarcodeAlertDialog(requireContext(), getViewLifecycleOwner(), this,
                Arrays.asList(BarcodeFormat.CODE_128,
                        BarcodeFormat.EAN_8,
                        BarcodeFormat.EAN_13,
                        BarcodeFormat.CODE_39,
                        BarcodeFormat.UPC_A,
                        BarcodeFormat.UPC_E,
                        BarcodeFormat.ITF), false);
    }


    @Override
    public boolean onBarcodeResult(@NotNull Result result) {
        viewModel.resultText.set(result.getText());
        return false;
    }
```

**Comment by kroegerama** [comment]
Release 1.0.3 should fix this crash :)

**Comment by alvindizon** [comment]
@kroegerama Thanks for fixing the crash... however it seems that I can't detect anything? Still using the same code I posted. Closing this issue anyway
